type Card = { title: string; copy: string };

type PageContent = {
  microcopy: string;
  leakEyebrow: string;
  leakTitle: string;
  leaks: Card[];
  operatorsEyebrow: string;
  operatorsTitle: string;
  packageAudience: [string, string, string];
  packageCopy: [string, string, string];
  packageAction: string;
  matchDescription: string;
  progress: { business: string; leak: string; complete: string; chooseBusiness: string; chooseLeak: string; ready: string; businessLabel: string; leakLabel: string; matchLabel: string };
  businessQuestion: string;
  businessOptions: [string, string, string];
  leakQuestion: string;
  leakOptions: [string, string, string];
  back: string;
  auditBrief: string;
  restart: string;
  sprintEyebrow: string;
  sprintTitle: string;
  sprintCopy: string;
  sprintAction: string;
  statusEyebrow: string;
  statusTitle: string;
  operational: string;
  finalEyebrow: string;
  finalTitle: string;
  finalCopy: string;
  chatButton: string;
  chatSubtitle: string;
  send: string;
};

export const localizedContent: Record<string, PageContent> = {
  en: {
    microcopy: "Built for service businesses, clinics, and agencies that need a clearer visitor handoff.", leakEyebrow: "The Revenue Leak", leakTitle: "Where websites lose customers.", leaks: [{ title: "No Answer", copy: "Visitors have buying questions, but the website only gives a form, phone number, or generic copy." }, { title: "Slow Response", copy: "A visitor signals intent, but the business responds after interest has cooled." }, { title: "Weak Qualification", copy: "The business receives vague messages instead of useful service, location, urgency, and contact details." }, { title: "Broken Handoff", copy: "The conversation never becomes a quote request, appointment request, or booked next step." }], operatorsEyebrow: "Operator Packages", operatorsTitle: "Three operators. One clear handoff.", packageAudience: ["For home services", "For clinics & aesthetics", "For agencies & consultants"], packageCopy: ["Captures job requests, service areas, urgency, and the cleanest next handoff.", "Captures appointment intent and reception questions with safe, structured handoff.", "Captures buyer questions, objections, and discovery-call intent before proposals stall."], packageAction: "Explore", matchDescription: "Answer two operational questions to surface the right MindReply operator and a focused audit brief. This quick match runs in your browser and does not collect or store your responses.", progress: { business: "Step 1 of 2", leak: "Step 2 of 2", complete: "Match complete", chooseBusiness: "Choose your business model", chooseLeak: "Choose the biggest drop-off", ready: "Your recommended operator is ready", businessLabel: "Business", leakLabel: "Leak", matchLabel: "Match" }, businessQuestion: "Where do visitor questions usually turn into revenue?", businessOptions: ["Home services", "Clinic or aesthetics", "Agency or consulting"], leakQuestion: "Which visitor moment currently costs you the most?", leakOptions: ["Questions go unanswered", "Follow-up arrives too late", "Interest never becomes a next step"], back: "← Back to business model", auditBrief: "Build my audit brief", restart: "Start over", sprintEyebrow: "The Setup Sprint", sprintTitle: "Find the leak. Map the response. Launch the operator.", sprintCopy: "A focused implementation that moves from visitor questions to qualified next actions without a drawn-out project.", sprintAction: "Start with the audit", statusEyebrow: "Operator Status", statusTitle: "Ready when visitor intent arrives.", operational: "Operational", finalEyebrow: "Stop losing warm visitors", finalTitle: "Find your highest-value leak first.", finalCopy: "Request a MindReply Website Leak Audit and we will map the next best handoff.", chatButton: "Ask MindReply Operator", chatSubtitle: "Guided next steps", send: "Send message" },
  es: {
    microcopy: "Para negocios de servicios, clínicas y agencias que necesitan un mejor traspaso de visitantes.", leakEyebrow: "La fuga de ingresos", leakTitle: "Dónde los sitios web pierden clientes.", leaks: [{ title: "Sin respuesta", copy: "Los visitantes tienen preguntas de compra, pero el sitio solo ofrece un formulario o un teléfono." }, { title: "Respuesta lenta", copy: "Un visitante muestra intención, pero el interés se enfría antes de recibir respuesta." }, { title: "Calificación débil", copy: "El negocio recibe mensajes vagos en lugar de información útil para actuar." }, { title: "Traspaso roto", copy: "La conversación nunca se convierte en una solicitud, cita o siguiente paso." }], operatorsEyebrow: "Paquetes de operadores", operatorsTitle: "Tres operadores. Un traspaso claro.", packageAudience: ["Para servicios a domicilio", "Para clínicas y estética", "Para agencias y consultores"], packageCopy: ["Captura solicitudes, zonas de servicio, urgencia y el mejor siguiente paso.", "Captura intención de cita y preguntas de recepción con un traspaso seguro.", "Capta preguntas de compradores, objeciones e intención de llamada antes de que se enfríe una propuesta."], packageAction: "Explorar", matchDescription: "Responde dos preguntas operativas para encontrar el operador MindReply adecuado y un resumen de auditoría. Esta selección funciona en tu navegador y no almacena respuestas.", progress: { business: "Paso 1 de 2", leak: "Paso 2 de 2", complete: "Selección completada", chooseBusiness: "Elige tu modelo de negocio", chooseLeak: "Elige el mayor punto de fuga", ready: "Tu operador recomendado está listo", businessLabel: "Negocio", leakLabel: "Fuga", matchLabel: "Resultado" }, businessQuestion: "¿Dónde suelen convertirse las preguntas de visitantes en ingresos?", businessOptions: ["Servicios a domicilio", "Clínica o estética", "Agencia o consultoría"], leakQuestion: "¿Qué momento de visitante te cuesta más hoy?", leakOptions: ["Las preguntas quedan sin respuesta", "El seguimiento llega tarde", "El interés no se convierte en siguiente paso"], back: "← Volver al negocio", auditBrief: "Crear mi resumen de auditoría", restart: "Empezar de nuevo", sprintEyebrow: "Sprint de activación", sprintTitle: "Encuentra la fuga. Define la respuesta. Lanza el operador.", sprintCopy: "Una implementación enfocada que convierte preguntas de visitantes en acciones cualificadas.", sprintAction: "Empezar con la auditoría", statusEyebrow: "Estado de operadores", statusTitle: "Listos cuando llega la intención.", operational: "Operativo", finalEyebrow: "No pierdas visitantes interesados", finalTitle: "Encuentra primero tu fuga de mayor valor.", finalCopy: "Solicita una auditoría MindReply y definiremos el mejor siguiente traspaso.", chatButton: "Preguntar a MindReply", chatSubtitle: "Próximos pasos guiados", send: "Enviar mensaje" },
  "pt-BR": {
    microcopy: "Para empresas de serviços, clínicas e agências que precisam de uma passagem mais clara para o visitante.", leakEyebrow: "A perda de receita", leakTitle: "Onde os sites perdem clientes.", leaks: [{ title: "Sem resposta", copy: "Visitantes têm perguntas de compra, mas o site oferece apenas formulário ou telefone." }, { title: "Resposta lenta", copy: "O visitante demonstra intenção, mas o interesse esfria antes da resposta." }, { title: "Qualificação fraca", copy: "A empresa recebe mensagens vagas em vez de informações úteis para agir." }, { title: "Passagem quebrada", copy: "A conversa não vira pedido, agendamento ou próximo passo." }], operatorsEyebrow: "Pacotes de operadores", operatorsTitle: "Três operadores. Uma passagem clara.", packageAudience: ["Para serviços residenciais", "Para clínicas e estética", "Para agências e consultores"], packageCopy: ["Captura pedidos, área de serviço, urgência e a melhor próxima ação.", "Captura intenção de consulta e dúvidas de recepção com passagem estruturada.", "Capta dúvidas de compradores, objeções e intenção de descoberta antes da proposta esfriar."], packageAction: "Explorar", matchDescription: "Responda a duas perguntas para encontrar o operador MindReply adequado e um resumo de auditoria. Esta seleção funciona no seu navegador e não armazena respostas.", progress: { business: "Etapa 1 de 2", leak: "Etapa 2 de 2", complete: "Correspondência concluída", chooseBusiness: "Escolha seu modelo de negócio", chooseLeak: "Escolha o maior ponto de perda", ready: "Seu operador recomendado está pronto", businessLabel: "Negócio", leakLabel: "Perda", matchLabel: "Resultado" }, businessQuestion: "Onde as perguntas dos visitantes normalmente viram receita?", businessOptions: ["Serviços residenciais", "Clínica ou estética", "Agência ou consultoria"], leakQuestion: "Qual momento do visitante custa mais hoje?", leakOptions: ["Perguntas ficam sem resposta", "O acompanhamento chega tarde", "O interesse não vira próximo passo"], back: "← Voltar ao negócio", auditBrief: "Criar meu resumo de auditoria", restart: "Começar de novo", sprintEyebrow: "Sprint de implementação", sprintTitle: "Encontre a perda. Mapeie a resposta. Lance o operador.", sprintCopy: "Uma implementação focada que transforma perguntas de visitantes em ações qualificadas.", sprintAction: "Começar com a auditoria", statusEyebrow: "Status dos operadores", statusTitle: "Pronto quando chega a intenção.", operational: "Operacional", finalEyebrow: "Pare de perder visitantes interessados", finalTitle: "Encontre primeiro sua perda de maior valor.", finalCopy: "Solicite uma auditoria MindReply e vamos mapear a melhor passagem.", chatButton: "Falar com MindReply", chatSubtitle: "Próximos passos guiados", send: "Enviar mensagem" },
  de: {
    microcopy: "Für Dienstleistungsbetriebe, Kliniken und Agenturen mit einem klareren Besucherübergang.", leakEyebrow: "Die Umsatzlücke", leakTitle: "Wo Websites Kunden verlieren.", leaks: [{ title: "Keine Antwort", copy: "Besucher haben Kauffragen, doch die Website bietet nur Formular oder Telefonnummer." }, { title: "Langsame Antwort", copy: "Ein Besucher signalisiert Interesse, aber die Aufmerksamkeit sinkt vor der Antwort." }, { title: "Schwache Qualifizierung", copy: "Das Unternehmen erhält vage Nachrichten statt verwertbarer Informationen." }, { title: "Unterbrochene Übergabe", copy: "Das Gespräch wird nie zu Anfrage, Termin oder nächstem Schritt." }], operatorsEyebrow: "Operator-Pakete", operatorsTitle: "Drei Operatoren. Eine klare Übergabe.", packageAudience: ["Für Heimdienstleistungen", "Für Kliniken und Ästhetik", "Für Agenturen und Beratung"], packageCopy: ["Erfasst Aufträge, Servicegebiet, Dringlichkeit und den besten nächsten Schritt.", "Erfasst Terminabsicht und Empfangsfragen mit strukturierter Übergabe.", "Erfasst Käuferfragen, Einwände und Discovery-Call-Absicht, bevor Angebote ins Stocken geraten."], packageAction: "Entdecken", matchDescription: "Beantworten Sie zwei Fragen für den passenden MindReply-Operator und ein fokussiertes Audit-Briefing. Die Auswahl läuft im Browser und speichert keine Antworten.", progress: { business: "Schritt 1 von 2", leak: "Schritt 2 von 2", complete: "Abgleich abgeschlossen", chooseBusiness: "Wählen Sie Ihr Geschäftsmodell", chooseLeak: "Wählen Sie die größte Lücke", ready: "Ihr empfohlener Operator ist bereit", businessLabel: "Geschäft", leakLabel: "Lücke", matchLabel: "Abgleich" }, businessQuestion: "Wo werden Besucherfragen meist zu Umsatz?", businessOptions: ["Heimdienstleistungen", "Klinik oder Ästhetik", "Agentur oder Beratung"], leakQuestion: "Welcher Besuchermoment kostet Sie aktuell am meisten?", leakOptions: ["Fragen bleiben unbeantwortet", "Nachfassen kommt zu spät", "Interesse wird kein nächster Schritt"], back: "← Zurück zum Geschäftsmodell", auditBrief: "Mein Audit-Briefing erstellen", restart: "Neu starten", sprintEyebrow: "Einrichtungs-Sprint", sprintTitle: "Lücke finden. Antwort planen. Operator starten.", sprintCopy: "Eine fokussierte Umsetzung, die Besucherfragen in qualifizierte Aktionen verwandelt.", sprintAction: "Mit dem Audit starten", statusEyebrow: "Operator-Status", statusTitle: "Bereit, wenn Besucherabsicht ankommt.", operational: "Betriebsbereit", finalEyebrow: "Verlieren Sie keine interessierten Besucher", finalTitle: "Finden Sie zuerst Ihre wertvollste Lücke.", finalCopy: "Fordern Sie ein MindReply-Audit an und wir planen die beste nächste Übergabe.", chatButton: "MindReply fragen", chatSubtitle: "Geführte nächste Schritte", send: "Nachricht senden" },
  fr: {
    microcopy: "Pour les entreprises de services, cliniques et agences qui ont besoin d’un passage visiteur plus clair.", leakEyebrow: "La fuite de revenus", leakTitle: "Où les sites perdent des clients.", leaks: [{ title: "Aucune réponse", copy: "Les visiteurs ont des questions d’achat, mais le site n’offre qu’un formulaire ou un téléphone." }, { title: "Réponse lente", copy: "Un visiteur manifeste son intention, mais l’attention baisse avant la réponse." }, { title: "Qualification faible", copy: "L’entreprise reçoit des messages vagues au lieu d’informations exploitables." }, { title: "Relais rompu", copy: "La conversation ne devient jamais demande, rendez-vous ou prochaine étape." }], operatorsEyebrow: "Offres opérateur", operatorsTitle: "Trois opérateurs. Un relais clair.", packageAudience: ["Pour les services à domicile", "Pour les cliniques et l’esthétique", "Pour les agences et consultants"], packageCopy: ["Capte demandes, zone de service, urgence et prochaine action claire.", "Capte l’intention de rendez-vous et les questions d’accueil avec un relais structuré.", "Capte questions acheteurs, objections et intention de découverte avant qu’une proposition ne bloque."], packageAction: "Explorer", matchDescription: "Répondez à deux questions pour trouver le bon opérateur MindReply et un brief d’audit ciblé. Ce choix fonctionne dans votre navigateur et ne stocke pas vos réponses.", progress: { business: "Étape 1 sur 2", leak: "Étape 2 sur 2", complete: "Correspondance terminée", chooseBusiness: "Choisissez votre modèle d’activité", chooseLeak: "Choisissez le plus grand point de fuite", ready: "Votre opérateur recommandé est prêt", businessLabel: "Activité", leakLabel: "Fuite", matchLabel: "Résultat" }, businessQuestion: "Où les questions visiteurs deviennent-elles généralement du revenu ?", businessOptions: ["Services à domicile", "Clinique ou esthétique", "Agence ou conseil"], leakQuestion: "Quel moment visiteur vous coûte le plus aujourd’hui ?", leakOptions: ["Les questions restent sans réponse", "Le suivi arrive trop tard", "L’intérêt ne devient pas une prochaine étape"], back: "← Retour à l’activité", auditBrief: "Créer mon brief d’audit", restart: "Recommencer", sprintEyebrow: "Sprint de configuration", sprintTitle: "Trouvez la fuite. Cartographiez la réponse. Lancez l’opérateur.", sprintCopy: "Une mise en œuvre ciblée qui transforme les questions visiteurs en actions qualifiées.", sprintAction: "Commencer par l’audit", statusEyebrow: "Statut des opérateurs", statusTitle: "Prêt lorsque l’intention arrive.", operational: "Opérationnel", finalEyebrow: "Ne perdez plus les visiteurs engagés", finalTitle: "Trouvez d’abord votre fuite la plus rentable.", finalCopy: "Demandez un audit MindReply et nous définirons le meilleur relais suivant.", chatButton: "Demander à MindReply", chatSubtitle: "Prochaines étapes guidées", send: "Envoyer le message" },
  ar: {
    microcopy: "للشركات الخدمية والعيادات والوكالات التي تحتاج إلى انتقال أوضح للزائر.", leakEyebrow: "تسرب الإيرادات", leakTitle: "أين تخسر المواقع العملاء.", leaks: [{ title: "لا توجد إجابة", copy: "لدى الزوار أسئلة شرائية، لكن الموقع يقدم نموذجاً أو رقم هاتف فقط." }, { title: "استجابة بطيئة", copy: "يوضح الزائر نيته، لكن اهتمامه يبرد قبل وصول الرد." }, { title: "تأهيل ضعيف", copy: "تتلقى الشركة رسائل غامضة بدلاً من معلومات قابلة للتنفيذ." }, { title: "تسليم معطل", copy: "لا تتحول المحادثة إلى طلب أو موعد أو خطوة تالية." }], operatorsEyebrow: "باقات المشغّلات", operatorsTitle: "ثلاثة مشغّلات. تسليم واحد واضح.", packageAudience: ["للخدمات المنزلية", "للعيادات والتجميل", "للوكالات والاستشاريين"], packageCopy: ["يلتقط الطلبات ومنطقة الخدمة والاستعجال والخطوة التالية الواضحة.", "يلتقط نية الموعد وأسئلة الاستقبال بتسليم منظم.", "يلتقط أسئلة المشترين والاعتراضات ونية المكالمة قبل تعطل العرض."], packageAction: "استكشف", matchDescription: "أجب عن سؤالين للعثور على مشغّل MindReply المناسب وملخص تدقيق مركز. يعمل الاختيار في متصفحك ولا يخزن إجاباتك.", progress: { business: "الخطوة 1 من 2", leak: "الخطوة 2 من 2", complete: "اكتملت المطابقة", chooseBusiness: "اختر نموذج عملك", chooseLeak: "اختر أكبر نقطة تسرب", ready: "مشغّلك الموصى به جاهز", businessLabel: "العمل", leakLabel: "التسرب", matchLabel: "المطابقة" }, businessQuestion: "أين تتحول أسئلة الزوار عادة إلى إيرادات؟", businessOptions: ["خدمات منزلية", "عيادة أو تجميل", "وكالة أو استشارات"], leakQuestion: "أي لحظة للزائر تكلفك أكثر اليوم؟", leakOptions: ["الأسئلة بلا إجابة", "المتابعة تصل متأخرة", "الاهتمام لا يصبح خطوة تالية"], back: "→ العودة إلى نموذج العمل", auditBrief: "إنشاء ملخص التدقيق", restart: "ابدأ من جديد", sprintEyebrow: "سباق الإعداد", sprintTitle: "اكتشف التسرب. ارسم الاستجابة. أطلق المشغّل.", sprintCopy: "تنفيذ مركز يحول أسئلة الزوار إلى إجراءات مؤهلة.", sprintAction: "ابدأ بالتدقيق", statusEyebrow: "حالة المشغّلات", statusTitle: "جاهز عند وصول نية الزائر.", operational: "يعمل", finalEyebrow: "لا تفقد الزوار المهتمين", finalTitle: "اعثر أولاً على تسربك الأعلى قيمة.", finalCopy: "اطلب تدقيق MindReply وسنرسم أفضل تسليم تالٍ.", chatButton: "اسأل MindReply", chatSubtitle: "خطوات تالية موجهة", send: "إرسال الرسالة" },
  tr: {
    microcopy: "Daha net bir ziyaretçi devrine ihtiyaç duyan hizmet işletmeleri, klinikler ve ajanslar için.", leakEyebrow: "Gelir kaybı", leakTitle: "Web sitelerinin müşteri kaybettiği yer.", leaks: [{ title: "Yanıt yok", copy: "Ziyaretçilerin satın alma soruları var, ancak site yalnızca form veya telefon sunuyor." }, { title: "Yavaş yanıt", copy: "Ziyaretçi niyet gösterir, ancak yanıt gelmeden ilgi soğur." }, { title: "Zayıf niteleme", copy: "İşletme, eyleme geçirilebilir bilgi yerine belirsiz mesajlar alır." }, { title: "Kırık devir", copy: "Konuşma hiçbir zaman talep, randevu veya sonraki adıma dönüşmez." }], operatorsEyebrow: "Operatör paketleri", operatorsTitle: "Üç operatör. Tek net devir.", packageAudience: ["Ev hizmetleri için", "Klinik ve estetik için", "Ajans ve danışmanlar için"], packageCopy: ["Talepleri, hizmet bölgesini, aciliyeti ve net sonraki adımı yakalar.", "Randevu niyetini ve resepsiyon sorularını yapılandırılmış biçimde yakalar.", "Teklif ivmesi kaybolmadan alıcı sorularını, itirazları ve keşif niyetini yakalar."], packageAction: "İncele", matchDescription: "Doğru MindReply operatörünü ve odaklı denetim özetini bulmak için iki soruyu yanıtlayın. Bu seçim tarayıcınızda çalışır ve yanıtları saklamaz.", progress: { business: "2 adımın 1'i", leak: "2 adımın 2'si", complete: "Eşleşme tamamlandı", chooseBusiness: "İş modelinizi seçin", chooseLeak: "En büyük kayıp noktasını seçin", ready: "Önerilen operatörünüz hazır", businessLabel: "İşletme", leakLabel: "Kayıp", matchLabel: "Eşleşme" }, businessQuestion: "Ziyaretçi soruları genellikle nerede gelire dönüşür?", businessOptions: ["Ev hizmetleri", "Klinik veya estetik", "Ajans veya danışmanlık"], leakQuestion: "Hangi ziyaretçi anı bugün size en çok kaybettiriyor?", leakOptions: ["Sorular yanıtsız kalıyor", "Takip çok geç geliyor", "İlgi sonraki adıma dönüşmüyor"], back: "← İş modeline dön", auditBrief: "Denetim özetimi oluştur", restart: "Yeniden başlat", sprintEyebrow: "Kurulum sprinti", sprintTitle: "Kaybı bulun. Yanıtı eşleyin. Operatörü başlatın.", sprintCopy: "Ziyaretçi sorularını nitelikli eylemlere dönüştüren odaklı bir uygulama.", sprintAction: "Denetimle başla", statusEyebrow: "Operatör durumu", statusTitle: "Ziyaretçi niyeti geldiğinde hazır.", operational: "Çalışıyor", finalEyebrow: "İlgili ziyaretçileri kaybetmeyin", finalTitle: "Önce en değerli kaybınızı bulun.", finalCopy: "MindReply denetimi isteyin, en iyi sonraki devri eşleyelim.", chatButton: "MindReply'e sor", chatSubtitle: "Yönlendirilmiş sonraki adımlar", send: "Mesaj gönder" },
  nl: {
    microcopy: "Voor dienstverleners, klinieken en bureaus die een duidelijkere bezoekerhandoff nodig hebben.", leakEyebrow: "Het omzetlek", leakTitle: "Waar websites klanten verliezen.", leaks: [{ title: "Geen antwoord", copy: "Bezoekers hebben koopvragen, maar de site biedt alleen een formulier of telefoonnummer." }, { title: "Trage reactie", copy: "Een bezoeker toont intentie, maar de aandacht daalt voordat er antwoord komt." }, { title: "Zwakke kwalificatie", copy: "Het bedrijf ontvangt vage berichten in plaats van bruikbare informatie." }, { title: "Gebroken handoff", copy: "Het gesprek wordt nooit een aanvraag, afspraak of volgende stap." }], operatorsEyebrow: "Operatorpakketten", operatorsTitle: "Drie operators. Eén duidelijke handoff.", packageAudience: ["Voor thuisdiensten", "Voor klinieken en esthetiek", "Voor bureaus en consultants"], packageCopy: ["Legt aanvragen, servicegebied, urgentie en de duidelijkste volgende stap vast.", "Legt afspraakintentie en receptievragen vast met een gestructureerde handoff.", "Legt kopersvragen, bezwaren en discovery-intentie vast voordat voorstellen stilvallen."], packageAction: "Verkennen", matchDescription: "Beantwoord twee vragen om de juiste MindReply-operator en een gerichte auditbrief te vinden. Deze keuze werkt in uw browser en slaat antwoorden niet op.", progress: { business: "Stap 1 van 2", leak: "Stap 2 van 2", complete: "Match voltooid", chooseBusiness: "Kies uw bedrijfsmodel", chooseLeak: "Kies het grootste lek", ready: "Uw aanbevolen operator staat klaar", businessLabel: "Bedrijf", leakLabel: "Lek", matchLabel: "Match" }, businessQuestion: "Waar worden bezoekersvragen meestal omzet?", businessOptions: ["Thuisdiensten", "Kliniek of esthetiek", "Bureau of advies"], leakQuestion: "Welk bezoekersmoment kost u vandaag het meest?", leakOptions: ["Vragen blijven onbeantwoord", "Opvolging komt te laat", "Interesse wordt geen volgende stap"], back: "← Terug naar bedrijfsmodel", auditBrief: "Mijn auditbrief maken", restart: "Opnieuw beginnen", sprintEyebrow: "Implementatiesprint", sprintTitle: "Vind het lek. Breng de reactie in kaart. Lanceer de operator.", sprintCopy: "Een gerichte implementatie die bezoekersvragen omzet in gekwalificeerde acties.", sprintAction: "Begin met de audit", statusEyebrow: "Operatorstatus", statusTitle: "Klaar wanneer bezoekersintentie arriveert.", operational: "Operationeel", finalEyebrow: "Verlies geen warme bezoekers", finalTitle: "Vind eerst uw meest waardevolle lek.", finalCopy: "Vraag een MindReply-audit aan en we brengen de beste volgende handoff in kaart.", chatButton: "Vraag MindReply", chatSubtitle: "Begeleide volgende stappen", send: "Bericht versturen" },
};
